// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AlisIptalEt(arg1) {
  return window['go']['main']['Uygulama']['AlisIptalEt'](arg1);
}

export function AlisOlustur(arg1) {
  return window['go']['main']['Uygulama']['AlisOlustur'](arg1);
}

export function AlislariListele(arg1, arg2, arg3) {
  return window['go']['main']['Uygulama']['AlislariListele'](arg1, arg2, arg3);
}

export function AyarGetir(arg1) {
  return window['go']['main']['Uygulama']['AyarGetir'](arg1);
}

export function AyarKaydet(arg1, arg2) {
  return window['go']['main']['Uygulama']['AyarKaydet'](arg1, arg2);
}

export function CariGetir(arg1) {
  return window['go']['main']['Uygulama']['CariGetir'](arg1);
}

export function CariHareketGuncelle(arg1) {
  return window['go']['main']['Uygulama']['CariHareketGuncelle'](arg1);
}

export function CariHareketOlustur(arg1) {
  return window['go']['main']['Uygulama']['CariHareketOlustur'](arg1);
}

export function CariHareketSil(arg1) {
  return window['go']['main']['Uygulama']['CariHareketSil'](arg1);
}

export function CariHareketleriListele(arg1) {
  return window['go']['main']['Uygulama']['CariHareketleriListele'](arg1);
}

export function CariKaydet(arg1) {
  return window['go']['main']['Uygulama']['CariKaydet'](arg1);
}

export function CariSil(arg1) {
  return window['go']['main']['Uygulama']['CariSil'](arg1);
}

export function CarileriListele(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['Uygulama']['CarileriListele'](arg1, arg2, arg3, arg4, arg5);
}

export function DashboardGetir(arg1, arg2) {
  return window['go']['main']['Uygulama']['DashboardGetir'](arg1, arg2);
}

export function DosyaSec() {
  return window['go']['main']['Uygulama']['DosyaSec']();
}

export function ExcelExportKaydet(arg1, arg2) {
  return window['go']['main']['Uygulama']['ExcelExportKaydet'](arg1, arg2);
}

export function ExcelExportOlustur(arg1) {
  return window['go']['main']['Uygulama']['ExcelExportOlustur'](arg1);
}

export function ExcelImport(arg1) {
  return window['go']['main']['Uygulama']['ExcelImport'](arg1);
}

export function ExcelImportKontrol(arg1) {
  return window['go']['main']['Uygulama']['ExcelImportKontrol'](arg1);
}

export function ExcelYedekKaydet(arg1) {
  return window['go']['main']['Uygulama']['ExcelYedekKaydet'](arg1);
}

export function ExcelYedekSayisiGetir() {
  return window['go']['main']['Uygulama']['ExcelYedekSayisiGetir']();
}

export function GecikmisOdemelerGetir(arg1) {
  return window['go']['main']['Uygulama']['GecikmisOdemelerGetir'](arg1);
}

export function KlasorSec() {
  return window['go']['main']['Uygulama']['KlasorSec']();
}

export function KullaniciCikis() {
  return window['go']['main']['Uygulama']['KullaniciCikis']();
}

export function KullaniciDogrula(arg1) {
  return window['go']['main']['Uygulama']['KullaniciDogrula'](arg1);
}

export function KullaniciEkle(arg1) {
  return window['go']['main']['Uygulama']['KullaniciEkle'](arg1);
}

export function KullaniciGiris(arg1, arg2) {
  return window['go']['main']['Uygulama']['KullaniciGiris'](arg1, arg2);
}

export function KullaniciListele() {
  return window['go']['main']['Uygulama']['KullaniciListele']();
}

export function KullaniciSifreDegistir(arg1, arg2) {
  return window['go']['main']['Uygulama']['KullaniciSifreDegistir'](arg1, arg2);
}

export function KullaniciSil(arg1) {
  return window['go']['main']['Uygulama']['KullaniciSil'](arg1);
}

export function LogKaydet(arg1, arg2) {
  return window['go']['main']['Uygulama']['LogKaydet'](arg1, arg2);
}

export function LoglariListele(arg1, arg2) {
  return window['go']['main']['Uygulama']['LoglariListele'](arg1, arg2);
}

export function LoglariSil() {
  return window['go']['main']['Uygulama']['LoglariSil']();
}

export function SatisIptalEt(arg1) {
  return window['go']['main']['Uygulama']['SatisIptalEt'](arg1);
}

export function SatisOlustur(arg1) {
  return window['go']['main']['Uygulama']['SatisOlustur'](arg1);
}

export function SatislariListele(arg1, arg2, arg3) {
  return window['go']['main']['Uygulama']['SatislariListele'](arg1, arg2, arg3);
}

export function SilmeKoduGetir() {
  return window['go']['main']['Uygulama']['SilmeKoduGetir']();
}

export function SilmeKoduKaydet(arg1) {
  return window['go']['main']['Uygulama']['SilmeKoduKaydet'](arg1);
}

export function YedekAl() {
  return window['go']['main']['Uygulama']['YedekAl']();
}

export function YedekKlasoruAc() {
  return window['go']['main']['Uygulama']['YedekKlasoruAc']();
}

export function YedekSayisiGetir() {
  return window['go']['main']['Uygulama']['YedekSayisiGetir']();
}

export function YedekSonGetir() {
  return window['go']['main']['Uygulama']['YedekSonGetir']();
}

export function YedekVarsayilanKlasor() {
  return window['go']['main']['Uygulama']['YedekVarsayilanKlasor']();
}
