// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {modeller} from '../models';

export function AlisIptalEt(arg1:number):Promise<void>;

export function AlisOlustur(arg1:modeller.Alis):Promise<modeller.Alis>;

export function AlislariListele(arg1:string,arg2:number,arg3:number):Promise<modeller.SayfaliSonuc_cari_modeller_Alis_>;

export function AyarGetir(arg1:string):Promise<string>;

export function AyarKaydet(arg1:string,arg2:string):Promise<void>;

export function CariGetir(arg1:number):Promise<modeller.CariHesap>;

export function CariHareketGuncelle(arg1:modeller.CariHareket):Promise<modeller.CariHareket>;

export function CariHareketOlustur(arg1:modeller.CariHareket):Promise<modeller.CariHareket>;

export function CariHareketSil(arg1:number):Promise<void>;

export function CariHareketleriListele(arg1:number):Promise<Array<modeller.CariHareket>>;

export function CariKaydet(arg1:modeller.CariHesap):Promise<modeller.CariHesap>;

export function CariSil(arg1:number):Promise<void>;

export function CarileriListele(arg1:string,arg2:number,arg3:number,arg4:string,arg5:string):Promise<modeller.SayfaliSonuc_cari_modeller_CariHesap_>;

export function DashboardGetir(arg1:string,arg2:string):Promise<modeller.Dashboard>;

export function DosyaSec():Promise<string>;

export function ExcelExportKaydet(arg1:string,arg2:string):Promise<void>;

export function ExcelExportOlustur(arg1:string):Promise<void>;

export function ExcelImport(arg1:string):Promise<void>;

export function ExcelImportKontrol(arg1:string):Promise<modeller.ExcelImportKontrolSonuc>;

export function ExcelYedekKaydet(arg1:string):Promise<void>;

export function ExcelYedekSayisiGetir():Promise<number>;

export function GecikmisOdemelerGetir(arg1:number):Promise<Array<modeller.GecikmisOdemeli>>;

export function KlasorSec():Promise<string>;

export function KullaniciCikis():Promise<void>;

export function KullaniciDogrula(arg1:string):Promise<modeller.Kullanici>;

export function KullaniciEkle(arg1:modeller.Kullanici):Promise<modeller.Kullanici>;

export function KullaniciGiris(arg1:string,arg2:string):Promise<modeller.Kullanici>;

export function KullaniciListele():Promise<Array<modeller.Kullanici>>;

export function KullaniciSifreDegistir(arg1:number,arg2:string):Promise<void>;

export function KullaniciSil(arg1:number):Promise<void>;

export function LogKaydet(arg1:string,arg2:string):Promise<void>;

export function LoglariListele(arg1:number,arg2:number):Promise<modeller.SayfaliLog>;

export function LoglariSil():Promise<void>;

export function SatisIptalEt(arg1:number):Promise<void>;

export function SatisOlustur(arg1:modeller.Satis):Promise<modeller.Satis>;

export function SatislariListele(arg1:string,arg2:number,arg3:number):Promise<modeller.SayfaliSonuc_cari_modeller_Satis_>;

export function SilmeKoduGetir():Promise<string>;

export function SilmeKoduKaydet(arg1:string):Promise<void>;

export function YedekAl():Promise<void>;

export function YedekKlasoruAc():Promise<void>;

export function YedekSayisiGetir():Promise<number>;

export function YedekSonGetir():Promise<string>;

export function YedekVarsayilanKlasor():Promise<string>;
